[package]
name = "vault-manager"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = [ "full" ] }
sqlx = { version = "0.5", features = [ "sqlite", "runtime-tokio-rustls" ] }

rust-s3 = { version = "0.26.4" }

clap = { version = "2.33.3" }

