[package]
name = "vault-manager"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "src/vault-manager-impl",
    "src/crypto",
    "src/fs",
    "src/tmp",
    "src/cli"
]

[dependencies]
vault-manager-impl = { version = "0.1.0", path = "src/vault-manager-impl" }
tokio = { version = "1", features = [ "macros" ] }
