[package]
name = "database-macros"
version = "0.0.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
convert_case = "0.5"

[lib]
proc-macro = true
