BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "file_tag" (
	"file_id"	INTEGER NOT NULL,
	"tag_id"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "tag" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "file" (
	"id"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL UNIQUE,
	"path"	TEXT NOT NULL UNIQUE,
	"is_remote" INTEGER NOT NULL,
	"random_hash"	TEXT NOT NULL UNIQUE,
	"data_hash"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "endpoint" (
	"id"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "key" (
	"id"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "file_tag" VALUES (1,1);
INSERT INTO "tag" VALUES (1,'feet');
CREATE UNIQUE INDEX IF NOT EXISTS "tag_name" ON "tag" (
	"name"
);
CREATE UNIQUE INDEX IF NOT EXISTS "file_title" ON "file" (
	"title"	ASC
);
CREATE UNIQUE INDEX IF NOT EXISTS "file_random_hash" ON "file" (
	"random_hash"
);
CREATE UNIQUE INDEX IF NOT EXISTS "file_data_hash" ON "file" (
	"data_hash"
);
COMMIT;
