name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --all --release -- --nocapture
