name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: nightly
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --all --release -- --nocapture
      
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
